export const metadata = {
  title: 'Commette',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
         <head>
        <link rel="icon" href="/images/favicon.svg" />
      </head>
      <body>{children}</body>
    </html>
  )
}
